routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', 'HomeController@index')->name('welcome');
Route::post('/reservation','ReservationController@reserve')->name('reservation.reserve');

/*contct Route*/
Route::post('/contact','ContactController@sendMessage')->name('contact.send');
Auth::routes();

Route::group(['prefix'=>'admin','middleware'=>'auth','namespace'=>'admin'], function(){
	Route::get('dashboard','DashboardController@index')->name('admin.dashboard');
	/*slider Controller*/
	Route::resource('slider','SliderController');
	/*Category Controller*/
	Route::resource('category','CategoryController');
	/*ItemController*/
	Route::resource('item','ItemController');
	/*Reservation*/
	Route::get('reservation','ReservarionController@index')->name('reservation.index');
	Route::post('reservation/{id}','ReservarionController@status')->name('reservation.status');
	Route::delete('reservation/{id}','ReservarionController@destory')->name('reservation.destory');


	/*Admin Controller*/
	Route::get('contact','ContactController@index')->name('contact.index');
	Route::get('contact/{id}','ContactController@show')->name('contact.show');
	Route::delete('contact/{id}','ContactController@destory')->name('contact.destory');
});

resources/views/layouts/partial/footer.blade.php
<footer class="footer">
	<div class="container-fluid">
		<div class="copyright float-right">
			&copy;
			<script>
			document.write(new Date().getFullYear())
			</script>, Mahamudul <i class="material-icons">favorite</i> by
			<a href="#" target="_blank">RS Software.com</a> for a better web.
		</div>
	</div>
</footer>

resources/views/layouts/partial/msg.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if ($errors->any())
            @foreach ($errors->all() as $error)
            <div class="alert alert-danger">
                <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none'">×</button>
                <span>
                <b> Danger - </b> {{ $error }}</span>
            </div>
            @endforeach
            @endif
            @if(session('successMsg'))
            <div class="alert alert-success">
                <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none'">×</button>
                <span>
                <b> Success - </b> {{ session('successMsg') }}</span>
            </div>
            @endif
        </div>
    </div>
</div>

resources/views/layouts/partial/sidebar.blade.php
<div class="sidebar" data-color="purple" data-background-color="white" data-image="{{ asset('backend/img/sidebar-1.jpg')}}">
  <div class="logo">
    <a href="{{ route('admin.dashboard')}}" class="simple-text logo-normal">
      Hasan's Kitchen
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="{{ Request::is('admin/dashboard*') ? 'active': '' }}">
        <a class="nav-link" href="{{ route('admin.dashboard') }}">
          <i class="material-icons">dashboard</i>
          <p>Dashboard</p>
        </a>
      </li>
      <li class="{{ Request::is('admin/slider*') ? 'active': '' }}">
        <a class="nav-link" href="{{ route('slider.index') }}">
          <i class="material-icons">slideshow</i>
          <p>Slider</p>
        </a>
      </li>
      <li class="{{ Request::is('admin/category*') ? 'active': '' }}">
        <a class="nav-link" href="{{ route('category.index') }}">
          <i class="material-icons">category</i>
          <p>Category</p>
        </a>
      </li>
      <li class="{{ Request::is('admin/item*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('item.index')}}">
          <i class="material-icons">list</i>
          <p>Items</p>
        </a>
      </li>
      <li class="{{ Request::is('admin/reservation*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('reservation.index') }}">
          <i class="material-icons">chrome_reader_mode</i>
          <p>Reservations</p>
        </a>
      </li>
  
      <li class="{{ Request::is('admin/contact*') ? 'active' : ''}}">
        <a class="nav-link" href="{{ route('contact.index') }}">
          <i class="material-icons">message</i>
          <p>Contact Message</p>
        </a>
      </li>
    </ul>
  </div>
</div>

resources/views/layouts/partial/topbar.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand" href="#pablo">Hello {{ Auth::user()->name }}</a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
    <span class="sr-only">Toggle navigation</span>
    <span class="navbar-toggler-icon icon-bar"></span>
    <span class="navbar-toggler-icon icon-bar"></span>
    <span class="navbar-toggler-icon icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#pablo">
            <i class="material-icons">dashboard</i>
            <p class="d-lg-none d-md-block">
              Stats
            </p>
          </a>
        </li>        
        <li class="nav-item">
          <a class="nav-link" href="#pablo">
            <i class="material-icons">person</i>
            <p class="d-lg-none d-md-block">
              Account
            </p>
          </a>
        </li>
       <li>
            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                <i class="material-icons">exit_to_app</i>
            </a>
            <form id="logout-form" method="POST" action="{{ route('logout') }}" style="display: none">
                {{ csrf_field() }}
            </form>
        </li>
      </ul>
    </div>
  </div>
</nav>